web_S10222254/Models/Fine.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
namespace web_S10222254.Models
{
    public class Fine
    {
        [Display(Name = "Due Date")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd-MMM-yyyy}")]
        public DateTime DueDate { get; set; }



        [Display(Name = "Number of Books Overdue")]

        //specifies that value of NumBooksOverdue must be bwtn 1 and 10 inclusive, else display error message as shown
        [Range(1, 10, ErrorMessage = "Invalid value! Please enter a value from 1 to 10")]  
        public int NumBooksOverdue { get; set; }



        [Display(Name = "Number of Days Overdue")]
        public int NumDaysOverdue { get; set; }



        [Display(Name = "Fine Rate (SGD)")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:#,##0.00}")]
        public double FineRate { get; set; }



        [Display(Name = "Fine (SGD)")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:#,##0.00}")]
        public double FineAmt { get; set; }
    }
}

web_S10222254/Controllers/FineController.cs
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using web_S10222254.Models;
namespace web_S10222254.Controllers
{
    public class FineController : Controller
    {
        //called when user follows url: "/fine/calculate" through HttpGet
        //default is HttpGet, but i can also declare it
        public ActionResult Calculate()
        {
            //basicaly user must now log in properly with password and LoginID to enter Fine Controlle's View, else redirect to Index home page
            if ((HttpContext.Session.GetString("Role") == null) ||
            (HttpContext.Session.GetString("Role") != "Staff"))
            {
                return RedirectToAction("Index", "Home");
            }

            //initializing the data for model object 
            //Prepare the ViewData to be use in Calculate.cshtml view
            ViewData["ShowResult"] = false;  //setting "ShowResult" of ViewData to false so that won't print anything in View since it false
                                             //only print the value if ViewData["ShowResult"] is true
            Fine fine = new Fine();  //new model instance called "fine"
            fine.DueDate = DateTime.Today;
            fine.FineRate = 0.50;  //FineRate be 0.5 per day
            return View(fine);  //send model object to Calculate View to display the values 
        }



        //default is not HttpPost therefore need to indicate the annotation if the action is to response to HttpPost only
        //if i want something to happen when a submit button is clicked, HttpPost is required
        //HttpPost happens when you click a submit button in a form with method attribute of “Post”
        //called when user clicks at compute button in View form and post the data entered in from Controller through HttpPost
        [HttpPost]
        public ActionResult Calculate(Fine fine)
        {
            //add this if any of the property of the stated Model class requires validation
            // The fine object contains user inputs from view
            if (!ModelState.IsValid) // validation fails
            {
                return View(fine); // returns the view with errors
            }

            // Calculate the cumulative fine and its breakdown
            double fineTotal = 0.0;
            string fineBreakdown = "";

            for (int count = 1; count <= fine.NumBooksOverdue; count++)
            {
                double fineForEachBook = count * fine.FineRate *
                fine.NumDaysOverdue;
                fineTotal += fineForEachBook;
                fineBreakdown += "Overdue cost for Book " + count + " = $" +
                fineForEachBook.ToString("#,##0.00") +
               "<br />";
            }

            fine.FineAmt = fineTotal;
            // Prepare the ViewData to be used in Calculate.cshtml view
            ViewData["ShowResult"] = true;  //after calculating everything, set "ShowResult" key to true for display of calculated value
            ViewData["FineBreakdown"] = fineBreakdown;  //stored fineBreakdown into "FineBreakdown" key of ViewData
            // Route to Calculate.cshtml view to display result
            return View(fine);
        }
    }
}

web_S10222254/Views/Fine/Calculate.cshtml
@model web_S10222254.Models.Fine
@{
    ViewData["Title"] = "Fine Calculator";
}
<h4 class="PageTitle">Fine Calculator</h4>
<hr />

<form asp-controller="Fine" asp-action="Calculate" method="post">
    <fieldset class="FormContent">
        <legend>Input Data:</legend>


        @*implements a placeholder for display of valdation error message that dosent pertain to any field in the View*@
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>


        <div class="form-group row">
            <label asp-for="DueDate"
                   class="col-sm-4 col-form-label"></label>


            @*The tag helper a textbox with calendar for selecting the loan due date:*@
            @*use razor syntax to enforce that max date value that can be selected is the current date*@
            @*allow user to select the date from a calender*@
            <div class="col-sm-8 col-md-4">
                <input asp-for="DueDate" class="form-control" max="@DateTime.Today.ToString("yyyy-MM-dd")" />
            </div>
        </div>


        <div class="form-group row">
            <label asp-for="NumDaysOverdue" class="col-sm-4 col-form-label"></label>
            <div class="col-sm-8">
                <input asp-for="NumDaysOverdue" readonly class="form-control-plaintext" />
            </div>
        </div>


        <div class="form-group row">
            <label asp-for="FineRate" class="col-sm-4 col-form-label"></label>
            <div class="col-sm-8">
                <input asp-for="FineRate" readonly class="form-control-plaintext" />
                <span style="font-style:italic;">
                    (rate per day for the 1st book,
                    double for the 2nd, triple for the 3rd ...)
                </span>
            </div>
        </div>


        <div class="form-group row">
            <label asp-for="NumBooksOverdue"
                   class="col-sm-4 col-form-label"></label>
            <div class="col-sm-8 col-md-4">


                @*implements a textbox for entry of number of books overdue*@
                @*since NumBooksOverdue is int type we cannot use [Required] attribute to enforce entry of a number in this textbox
                    can only use "required" attribute to ensure user wont leave this textbox blank*@
                <input asp-for="NumBooksOverdue" class="form-control" required />


                @*and a placeholder for displaying any input data validation error message*@
                @*since we implmented that NumBooksOverdue can only be 1-10, violating the rule will cause custom error msg to 
                    appear in <span> tag*@
                <span asp-validation-for="NumBooksOverdue" class="text-danger"></span>


            </div>
        </div>
        <div class="form-group row">
            <div class="col-sm-8 offset-sm-4">
                <input type="submit" value="Compute"
                       class="btn btn-primary" />
            </div>
        </div>
    </fieldset>
</form>

<!--if ViewData["ShowResult"] is true show calulcated value-->
@if (Convert.ToBoolean(ViewData["ShowResult"]))
{
    <fieldset class="FormContent">
        <legend>Result:</legend>
        <div class="form-group row">
            <label asp-for="FineAmt" class="col-sm-4 col-form-label"></label>
            <div class="col-sm-8 form-control-plaintext">
                @Html.Display("FineAmt")
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-4 col-form-label">
                Breakdown of the Fine
            </label>
            <div class="col-sm-8 form-control-plaintext">


                @*ViewData["FineBreakdown"] contains fineBreakdown which is a list with HTML tage <br>, thus use .Raw to display everything in list in ViewData["FineBreakdown"] tgt with <br>*@
                @Html.Raw(ViewData["FineBreakdown"])


            </div>
        </div>
    </fieldset>
}
<script>
    // Calculate and display the days overdue when the due date is set
    document.getElementById("DueDate").onchange = function () {

        // The number of milliseconds in one day
        var oneday = 24 * 60 * 60 * 1000;
        var today = new Date();
        var dueDate = new Date(document.getElementById("DueDate").value);

        // Convert both dates to milliseconds
        var today_ms = today.getTime();
        var dueDate_ms = dueDate.getTime();

        // Calculate the difference in milliseconds
        var difference_ms = today_ms - dueDate_ms;

        // Convert back to days
        var numDayOverdue = Math.floor(difference_ms / oneday);

        // Assign the value to input field
        document.getElementById("NumDaysOverdue").value = numDayOverdue;
    };
</script>