web_S10222254/Models/Rental.cs
//Rental.cs is a simple text file under Models with properties of 2 classes RentalDiscount, Rental that will be used to contain data for the Rental Calculator
//RentalDiscount class is used to model the Discount checkbox choices on this page: 



using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
namespace web_S10222254.Models
{
    //Validation attributes: Required, StringLength, Range, RegularExpression, Compare
    //Required: show user default message “The CustName field is required” if user do not enter anything into the Required field
    //StringLength: specifies maximum and minimum length of the property
    //Range: specifies minimum and maximum constraints for a numerical value. 

    //Regular: are an efficient way to enforce the shape and contents of a string value. 
    //e.g. [RegularExpression(@"^[A-Z]+[a-zA-Z""'\s-]*$")]  ->  property must use only letters, first letter upercase, white space, numbers and special characters are not allowed

    //Compare: two properties of a model object have the same value (e.g. property called "EmailConfirm", if Compare("Email"), string entered for property "EmailConfirm" must be same as "Email"





    //first Model class: RentalDiscount
    //Properties: Description, DiscountPercent, Selected
    public class RentalDiscount
    {
        public string Description { get; set; }
        public double DiscountPercent { get; set; }
        public bool Selected { get; set; }
    }





    //second Model class: Rental 
    //Properties: LoanDate, NumBooks, NumDays, RentalRate, DueDate, RentalFee, DiscountPercent, Discounts, AmountPayable
    public class Rental
    {
        //'Display' attribute sets the friendly display name for a model property
        //why Display attribute is used? e.g. if more than one View uses Rental model class, Display attribute set here will be called automatically in the more than 1 View through: asp-for="LoanDate"
        //asp-for will link LoanDate property to the label and call its set data to be printed
        [Display(Name = "Loan Date")]  //for this case, for the property "LoanDate", instead of displaying the name "LoanDate" in the label, we use 'Display' attribute to display a user-friendly name "Loan Date"


        //'DataType' attribute sets enables us to provide the runtime with information about the specific purpose of the property
        [DataType(DataType.Date)]  //for this case, we set 'DataType' attribute for property "LoanDate" as 'DataType.Date', thus only the date is displayed, not time information
                                   //if there was a property called "Password", where we do not want it to be in readable format, we can use 'DataType.Password' for its 'DataType' attribute to make it non-readable to users


        //'DisplayFormat' attribute handles various formatting options for the property
        [DisplayFormat(DataFormatString = "{0:dd-MMM-yyyy}")]  //for this case, we will display property "LoanDate" in the format dd-MMM-yyyy
                                                               //we can also set 'ApplyFormatInEditMode' to true for 'DisplayFormat' attribute
                                                               //By default, ApplyFormatInEditMode is false because MVC binder might not to parse the value formatted for display only. 
        public DateTime LoanDate { get; set; }



        [Display(Name = "Number of Books")]
        public int NumBooks { get; set; }




        [Display(Name = "Number of Days")]
        public int NumDays { get; set; }


        
        [Display(Name = "Rental Rate (SGD)")]
        [DisplayFormat(DataFormatString = "{0:#,##0.00}")]  
        public double RentalRate { get; set; }
        


        [Display(Name = "Due Date")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd-MMM-yyyy}")]
        public DateTime DueDate { get; set; }



        [Display(Name = "Rental Fee (SGD)")]
        [DisplayFormat(DataFormatString = "{0:#,##0.00}")]
        public double RentalFee { get; set; }  //The value for RentalFee will be displayed with 2 decimal places, and punctuated (,) at the thousand mark.
        




        [Display(Name = "Discount Given (%)")]
        [DisplayFormat(DataFormatString = "{0:#0.0}")]  //value for DiscountPercent will be displayed with 1 decimal places with no punctuation
                                                        //if value is 4, end value will be 4.0 with 0 added at the back
        public double DiscountPercent { get; set; }



        [Display(Name = "Discount Given (%)")]
        public List<RentalDiscount> Discounts { get; set; }



        [Display(Name = "Amount Payable (SGD)")]
        [DisplayFormat(DataFormatString = "{0:#,##0.00}")]
        public int AmountPayable { get; set; }
    }
}

web_S10222254/Controllers/RentalController.cs
//in conlusion of week 2, ViewData and @model can be used to pass a data and call them from the Controller to a View using @ViewData["NameOfKey"] and @Model.NameOfKey
//to declare data into ViewData, use ViewData["NameOfKey"] = DataToBePassed
//to declare data into @model, take note of class of returned object in Controller's Action, in View page '@model web_s1234567.Models.NameOfObjectClass'
//to call a passed data using ViewData, must set ViewData["NameOfKey"] = NameOfDataToBePassed
//to call a passed data using @model, must have a returned object from an Action so that "@model web_s1234567.Models.NameOfClassOfReturnedObject" can be used in View to call the public properties of the object returned


//ViewData used to pass small data from Controller to View so that the small data can be viewed in View using @ViewData["NumBooks"]
//In conclusion of this Controller, 4 lists are declared to contain the list of choices for the Rental Calculation
//RentalController() first created to hard code and populate numBooks, discountList lists, where numBooks contains SelectListItem object of range 1-10 and discountList contains info on "Student Membership" & "Birthday Discount"
//First overload method, Calculate() is created. Main puprose: initialize default values for rental object, when validation error occurs, ViewData["ShowResult"] set to false since nothing to show due to error, set default values of rental object will be shown in View
//Second overload method, Calculate(Rental rental). Main purpose: when user enters correct value for Rental class object called rental, rental goes into this method, ViewData["ShowResult"] set to true since will hve rental's calculations to show, calculate properties like RentalFee, RentalRate etc., show View of rental end product





using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.Rendering;  //exposes the SelectListItem class which is used for binding data to a drop - down list.
                                           //represents the selected item in an instance of the "SelectListItem" class for this case

using web_S10222254.Models;  //exposes the model classes defined in the “Models” folder of our project
namespace web_S10222254.Controllers
{
    public class RentalController : Controller
    {
        //declaring 4 list of choices required for the Rental Calculation

        // List that stores the options for days (duration) of loan
        private List<int> numLoanDays = new List<int> { 2, 5, 10, 20 };

        // List that stores the corresponding rental rate for each options
        private List<double> rentalRates = new List<double> { 1.0, 1.50, 2.50, 5.00 };

        // A list for populating drop-down list of range 1 to 10 (SelectListItem only used for drop down)
        //"SelectListItem" class comes from line 4 using
        private List<SelectListItem> numBooks = new List<SelectListItem>();

        // A list for populating checkbox list, check between "Student Membership" & "Birthday Discount"
        //is a list of RentalDiscount instances, instance can have access to properties Description, DiscountPercent, Selected
        private List<RentalDiscount> discountList = new List<RentalDiscount>();





        // Constructor for the RentalController, used to populate numBooks and discountList lists
        //populate numBooks list with SelectListItem object with string(1-10) for its Value and Text
        //populate discountList list with 2 RentalDiscount objects for "Student Membership (20%)" and "Birthday Discount (10%)"
        public RentalController()
        {
            //Populate the selection list for drop-down list
            //Populate 10 items in "SelectListItem" object for binding to the drop-down list on the rental calculator view
            for (int i = 1; i <= 10; i++)
            {
                numBooks.Add(
                new SelectListItem  //properties of "SelectListItem" include Disabled, Group, Selected, Text, Value
                                    //a new "SelectListItem" object that has a Value of string(i) and Text string(i), where i is int 1 to 10
                {
                    Value = i.ToString(),
                    Text = i.ToString(),
                });
            }
        

            //Populate the selection list for checkboxes list with objects from "RentalDiscount" class
            //add 2 "RentalDiscount" objects which are to be bound to a checkbox list on the rental calculator view
            //there are 2 types of discounts, "Student Membership" & "Birthday Discount" with 20% and 10% discount respectively
            //"discountList" will have 2 RentalDiscount class objects for "Student Membership" & "Birthday Discount" with their respective Description, DiscountPercent & Selected property
            discountList.Add(
            new RentalDiscount
            {
                Description = "Student Membership (20%)",  //"Description" property contains text display for the checkbox
                DiscountPercent = 20,  //"DiscountPercent" property contains discount value for each checkbox choice
                Selected = false  //Bool value which will decide if it was checked or not
            });

            discountList.Add(
            new RentalDiscount
            {
                Description = "Birthday Discount (10%)",
                DiscountPercent = 10,
                Selected = false
            });
        }





        //First overload method, if there is validation error and need to return to the form for displaying error and correction.
        //Will display the form with rental object's initial/default values
        //called when user follows URL "~/Rental/Calculate" since "Calculate" method found in "RentalController"
        //in this method, i am setting default/initial values of rental object to return with View
        public ActionResult Calculate()
         {
            // Stop accessing the action if not logged in
            // or account not in the "Staff" role
            // if user does not enter corerct LoginID and password, Role will not be "Staff". Since Role is not "Staff" will redirect to Index Action of Home Controller instead
            if ((HttpContext.Session.GetString("Role") == null) ||
            (HttpContext.Session.GetString("Role") != "Staff"))
            {   
                return RedirectToAction("Index", "Home");
            }


            //Prepare the ViewData to be used in Calculate.cshtml view
            //"ViewData" is a dictionary of objects that are stored/retrieved using strings as keys
            //ViewData only transfers data from a Controller Action to the corresponding View, not vice-versa. ViewData values will be cleared if redirection occurs
            //transfers the lists (numBooks, numLoanDays) data to ViewData dictionary at index ("NumBooks", "NumDays") respectively. 
            //** e.g., @ViewData["NumBooks"] can be used to pass data of numBooks from RentalController to View 

            ViewData["ShowResult"] = false;  //"ShowResult" set to false, bc there is no result to show yet 
            ViewData["NumBooks"] = numBooks;  //transfering numBooks list into ViewData dict index "NumBooks"
            ViewData["NumDays"] = numLoanDays;  //transfering numLoanDays list into ViewData dict index "NumDays"


            //initializes default values for the rental model object which will be sent to the "Calculate" View
            //these default values are shown when validation error happens
            Rental rental = new Rental
            {
                //LoanDate var default value will be today's date
                LoanDate = DateTime.Today,

                //default value of NumBooks: int(Value = 1) of first SelectListItem class object from numBooks list
                //numBooks drop down list contains 10 objects of SelectListItem class, where Value & Text of each SelectListItem object are both string(1-10)
                //numBooks[0].Value will be Value = 1 of first SelectListItem object from numBooks list
                NumBooks = Convert.ToInt32(numBooks[0].Value),  //before user selects anything, will show "2" in drop down list 

                // Set the default number of days loaned to 2, where numLoanDays[0] = 2
                NumDays = numLoanDays[0],  //will check value "2" before user selects anything  

                //discountList is a list containing 2 RentalDiscount class objects with properties for "Student Membership" & "Birthday Discount"
                Discounts = discountList
            };
            
            //by returning rental, in Calculate.cshtml, @model MUST return the class of returned object here in the Controller
            //class of rental is Rental, so @mode IS declared for Rental
            return View(rental);  

            //rental object will have default values of:
            //  LoanDate: today date
            //, NumBooks: int(Value = 1) of first object in numBooks list
            //, NumDays: 2
            //, Discounts: discountList list containing 2 RentalDiscount class objects for "Student Membership" & "Birthday Discount"
        }





        [HttpPost]  //called when user  clicks at the Compute button, which will send data in a HTML form to the server via the HttpPost method
        //Second overload method will read the data selected by user from the rental object in Action's parameter,
        //compute the rental fee payable and update the computation result in the rental object to
        //route user back to the Calculate View with rental object to display the result of user's rental object
        public ActionResult Calculate(Rental rental)  //rental object keeps data entered by user
        {
            //initiated ViewData here again to ensure drop-down list (numBooks) & radio buttons list (numLoanDays) still contain their values

web_S10222254/Views/Rental/Calculate.cshtml
<!--This is a View used to show returned View of Action "Calculate" from RentalController-->

@*use razor syntax "@model" to bind Rental class to the View*@
@*@model IS Rental, used to access all the public properties from Rental class under Rental.cs, NOT RentalDiscount class*@
@*Calculate.cshtml is calling the properties of Rental using @Model, and is calling the properties of previously declared ViewData data in the Controller and here using  @ViewData["NameOfKey"]*@
@*e.g., <p>@Model.Rental.LoanDate</p> can be used to access the public property LoanDate from Rental class and display in the View*@
@*name of file containing the class is not important. Only the classes declared within is important.
    For this case, Rental.cs is a file containing 2 declared classes Rental and RentalDiscount
    @model IS declared class Rental from the Rental.cs file. File name is ignored, only focus on name of declared class*@

@*to use @model, i have to first create an Action that returns an object,
    then @model will .NameOfTheClassOfReturnedObject in the View to display public properties of NameOfTheClassOfReturnedObject
    then i can call the public properties of NameOfTheClassOfReturnedObject in the View using "@Model.NameOfTheClassOfReturnedObject.PublicPropertyName"*@

@*using @model makes this a strongly typed View*@

@model web_S10222254.Models.Rental



<!--use ViewData to specify the page title: "Calculate" to be displayed on web browser-->
@*ViewData can be used to store data that is not within @model class's public properties*@
<!--setting the value "Rental Calculator" to the key "Title" of your ViewData-->
@*e.g. can use @ViewData["Title"] for <title> in the View*@

@{
    ViewData["Title"] = "Rental Calculator";
}





Rental Calculator
<hr />
<form asp-controller="Rental" asp-action="Calculate" method="post">
    <!--when we click a "submit"button, it will go to Rental Controller Calculate Action-->
    <div>Input Data:</div>
    <div>
        <label asp-for="LoanDate"></label>  <!--<label> element is used to associate a text label with a firm <input> field, better usability for phone users-->
        <!--here, it will be rendered with declared attributes, Name = "Loan Date", type = date, DataFormatString = "{0:dd-MMM-yyyy}"-->
        <input asp-for="LoanDate" readonly />
    </div>




    @*drop down for number of books*@
    <div>

        <!--was declared for NumBooks to have [Display] attribute of "Number of Books"-->
        <!--"<label asp-for="NumBooks"></label>" will be rendered as "<label>for="NumBooks">Number of Books</label>"-->
        <label asp-for="NumBooks"></label>

        <!--calling the data of NumBooks from Rental class through ViewData and displaying it here-->
        @*@ViewData["NumBooks"] contains a list of SelectListItem instances, with Value and Text as string(1-10)*@
        <!--each instance in @ViewData["NumBooks"] will be shown as a list of SelectListItem, and allow user to select as options-->
        <select asp-for="NumBooks" asp-items="@ViewData["NumBooks"] as List<SelectListItem>"></select>

    </div>





    <!--radio button for number of days-->
    <div>
        <label asp-for="NumDays"></label>
        <div class="form-group form-check-inline">

            <!--tag helper implements a radio buttons list-->
            <!--ViewData["NumDays"] contains a list of numbers 2, 5, 10, 20-->
            @foreach (var item in ViewData["NumDays"] as List<int>)
            {
                <label>
                    <input asp-for="NumDays" type="radio" value="@item" />  <!--<input type="radio" value="2" checked="checked" id="NumDays" name="NumDays" />-->
                    <span>@item</span>
                </label>
            }

        </div>
    </div>




    <div>
        <label asp-for="Discounts"></label>
        <div class="form-group form-check-inline">

            @for (int i = 0; i < Model.Discounts.Count; i++)
            {
                <!--each instance of RentalDiscount list contains properties: Description, Selected, DiscountPercent-->

                <!--@Model -- Rental class-->
                <!--@Model.Discounts -- List<RentalDiscount>-->
                <!--@Model.Discounts[i] -- instance of RentalDiscount list, contains properties: Description, DiscountPercent and bool Selected-->
                <!--@Model.Discounts[i].Description -- string Description of each instance of list of RentalDiscount-->



                @*in conclusion, asp-for tag helper here is used to link the <input>, <label> to a particular model in the model class
            for the <label>, data to be shown in a label is the razor code @Model.Discounts[i].Description*@



                <!--Discounts list contains properties Description, DiscountPercent & bool Selected of 2 objects for "Student Membership" and "Birthday Discount"-->
                <!--each checkbox must have unqiue name and id-->
                <!--tag helper "asp-for" uses the Discounts[i].Selected property to give each checkbox unqiue name and id-->
                <!--e.g. for the first instance of Discounts, it will have its own unqiue name and id since
        asp-for="Discounts[0].Selected"  ->  for="Discounts[0].Selected"-->
                <input asp-for="Discounts[i].Selected" type="checkbox" /> <!--will show a checkbox for each instance in List<RentalDiscount>-->



                <!--for this, for each label for bool Selected property of each instance of RentalDiscount list, will have
        String Description of each instance of list of RentalDiscount-->
                <!--continue e.g., for="Discounts[0].Selected" print its Description property as label. for the specific instance of List<RentalDiscount>, print its Description-->
                <label asp-for="Discounts[i].Selected">@Model.Discounts[i].Description</label>




                <!--to pass the selected option of user for calculation in the system, have to pass DiscountPercent again but hidden into the system-->

                <!-- 2 Hidden fields to get value at server-side and states of checkbox list -->
                <!--continue e.g., for="Discounts[0].Selected" read its DiscountPercent property as a hidden input, for the "Student Membership" discount,
        it has DiscountPercent of 20%-->
                <input type="hidden"
                       asp-for="Discounts[i].DiscountPercent" />



                <!--contains the discount description, for the Controller to read the description when the form is posted,
        and to pass back to the View for display in the label element when rental result is completed-->
                <!--continue e.g., for="Discounts[0].Selected" read its Description property as a hidden input-->
                <input type="hidden"
                       asp-for="Discounts[i].Description" />






                <!--code that will run after input, label and 2 hidden input code above is excecuted-->

                @*<input type="checkbox" id="Discounts_0__Selected" name="Discounts[0].Selected" value="true" />
            <label for="Discounts_0__Selected">Student Membership (20%)</label>
            <input type="hidden" id="Discounts_0__DiscountPercent" name="Discounts[0].DiscountPercent" value="20" />
            <input type="hidden" id="Discounts_0__Description" name="Discounts[0].Description" value="Student Membership (20%)" />

            <input type="checkbox" id="Discounts_1__Selected" name="Discounts[1].Selected" value="true" />
            <label for="Discounts_1__Selected">Birthday Discount (10%)</label>
            <input type="hidden" id="Discounts_1__DiscountPercent" name="Discounts[1].DiscountPercent" value="10" />
            <input type="hidden" id="Discounts_1__Description" name="Discounts[1].Description" value="Birthday Discount (10%)" />*@

            }
        </div>
    </div>

    <div>
        <input type="submit" value="Compute" />
    </div>
</form>



<!--used to display the rental computation result when ViewData["ShowResult"] is true-->
@if (Convert.ToBoolean(ViewData["ShowResult"]))  @*if data from ViewData["ShowResult"] is true, print the results*@ 
{
    <span>Result:</span>
    <div>
        <label asp-for="DueDate"></label>
        @Html.Display("DueDate")  @*use @Html.Display to display the computed result as plain text in the View*@
    </div>
    <div>
        <label asp-for="RentalRate"></label>
        @Html.Display("RentalRate")  @*Html.Display can display public properties of model class*@
        (per book per day)
    </div>
    <div>
        <label asp-for="RentalFee"></label>
        @Html.Display("RentalFee")
    </div>
    <div>
        <label asp-for="DiscountPercent"></label>
        @Html.Display("DiscountPercent")
    </div>
    <div>
        <label asp-for="AmountPayable"></label>
        @Html.Display("AmountPayable")
    </div>
}